### ISSUE TITLE
API to execute queries from third party apps

### ISSUE THREAD

**Issue by acs** [StackExchange/StackExchange.DataExplorer#64]
It will be great to have an API so third party tools can execute queries in DataExplorer and use the data.

The same idea than "BigQuery API":https://cloud.google.com/bigquery/docs/reference/v2/ but probably simpler.

**Comment by rschrieken** [comment]
There is not much need for that as you can download the data for your own on-premises solution as explained [here](http://meta.stackexchange.com/questions/198915/is-there-a-direct-download-link-with-a-raw-data-dump-of-stack-overflow-not-a-t)

**Comment by NickCraver** [comment]
@rschrieken is correct. If you want to access the data in a much heavier fashion we do supply it directly for download quarterly for just that reason! 

The process for getting the data has actually gotten much simpler as we've moved to Archive.org for hosting. You can get it via direct download or via torrent here: https://archive.org/details/stackexchange

**Comment by acs** [comment]
Yes, our plan is to work directly with the full database. But for our first prototype is cheaper for us just using the great Data Explorer. And it is updated once a week. The full archive only each 3 months. After that, we plan to use the events API from StackExchange to complete the data.

Thank you very much for your quick response. Data Explorer is an amazing project. Near 400.000 queries already created by the community. The best data mining community in the world? Probably!

**Comment by NickCraver** [comment]
@acs understood. I'm closing this out because that simply isn't our plan for Data Explorer. The entire purpose of it is to offer a human interface to easily access and collaborate on access to the SQL data. The database server behind it isn't *that* awesome to handle a fully automated load - that's why we offer the data dump and the API which is live.

Good luck with whatever it is you're building, I'd love a ping knowing what it is! We are always amazed what the community builds with all this CC data, it's just one of many reasons we release it.

**Comment by acs** [comment]
@NickCraver thank you very much for the clarification. I am not sure that the StackExchange API is complete enough for our needs (detecting events related to keywords) son maybe we don't need to use the archive and just use the API directly.

Once we have finished our prototype I will share it with you. Not sure about the best place for doing it!
